# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('REV', 'EN REVISIÓN'), ('APP', 'APROBADO'), ('DEN', 'RECHAZADO')], max_length=100, null=True),
        ),
    ]
