# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('REV', 'EN REVISIÓN'), ('APP', 'APROBADO'), ('DEN', 'RECHAZADO')], default='REV', max_length=100, null=True),
        ),
    ]
