# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170210_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('EN REVISION', 'EN REVISION'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='REV', max_length=100, null=True),
        ),
    ]
